# Generated by Django 3.2.6 on 2022-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historialregistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_host', models.CharField(max_length=50)),
                ('dire_ip', models.CharField(max_length=50)),
                ('dire_puerto', models.CharField(max_length=50)),
                ('vulnerabilidad', models.CharField(max_length=200)),
                ('fecha_scaneo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'escaneo',
                'verbose_name_plural': 'escaneos',
            },
        ),
    ]
