# Generated by Django 3.1 on 2022-10-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEscaneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_host', models.CharField(max_length=50)),
                ('dire_ip', models.CharField(max_length=50)),
                ('dire_puerto', models.CharField(max_length=50)),
                ('vulnerabilidad', models.CharField(max_length=5000)),
                ('fecha_scaneo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'escaneo',
                'verbose_name_plural': 'escaneos',
            },
        ),
        migrations.CreateModel(
            name='tb_estadolb',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('estadolb', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tb_folder',
            fields=[
                ('idfolder', models.AutoField(primary_key=True, serialize=False)),
                ('tipofolder', models.CharField(max_length=50)),
                ('nombrefolder', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tb_folder',
                'verbose_name_plural': 'tb_folders',
            },
        ),
        migrations.CreateModel(
            name='tb_lb_host',
            fields=[
                ('hostid', models.AutoField(primary_key=True, serialize=False)),
                ('hostip', models.CharField(max_length=20)),
                ('hostfqdn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tb_lb_output',
            fields=[
                ('id_lboutput', models.AutoField(primary_key=True, serialize=False)),
                ('titulolb', models.TextField(max_length=4000)),
                ('subtitulolb', models.TextField(max_length=4000)),
                ('descrip1', models.TextField(max_length=4000)),
                ('descrip2', models.TextField(max_length=4000)),
            ],
            options={
                'verbose_name': 'tb_lb_output',
                'verbose_name_plural': 'tb_lb_outputs',
                'ordering': ['id_lboutput'],
            },
        ),
        migrations.CreateModel(
            name='tb_output',
            fields=[
                ('idoutput', models.AutoField(primary_key=True, serialize=False)),
                ('puertooutput', models.CharField(max_length=50)),
                ('output', models.TextField(max_length=4000)),
            ],
            options={
                'verbose_name': 'tb_output',
                'verbose_name_plural': 'tb_outputs',
                'ordering': ['idoutput'],
            },
        ),
        migrations.CreateModel(
            name='tb_plugin',
            fields=[
                ('id_plugin', models.AutoField(primary_key=True, serialize=False)),
                ('severidad', models.TextField(max_length=4000)),
                ('family', models.TextField(max_length=4000)),
                ('synopsis', models.TextField(max_length=4000)),
                ('descripcion', models.TextField(max_length=4000)),
                ('solution', models.TextField(max_length=4000)),
            ],
            options={
                'verbose_name': 'tb_plugin',
                'verbose_name_plural': 'tb_plugins',
                'ordering': ['id_plugin'],
            },
        ),
        migrations.CreateModel(
            name='tb_scan',
            fields=[
                ('idscan', models.AutoField(primary_key=True, serialize=False)),
                ('tiposcan', models.CharField(max_length=100)),
                ('nombrescan', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tb_scan',
                'verbose_name_plural': 'tb_scans'
            },
        ),
        migrations.CreateModel(
            name='tb_usuario',
            fields=[
                ('idusuarionuevo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreuser', models.CharField(max_length=50)),
                ('apellidouser', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('usermail', models.CharField(max_length=50)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tb_scan_run',
            fields=[
                ('idscanrun', models.AutoField(primary_key=True, serialize=False)),
                ('starscan', models.DateField(auto_now_add=True)),
                ('endscan', models.DateField(auto_now_add=True))
            ],
            options={
                'verbose_name': 'tb_scan_run',
                'verbose_name_plural': 'tb_scan_runs'
              
            },
        ),
        migrations.CreateModel(
            name='tb_host',
            fields=[
                ('id_tbhost', models.AutoField(primary_key=True, serialize=False)),
                ('idhost', models.CharField(max_length=50)),
                ('iphost', models.CharField(max_length=50)),
                ('fqdnhost', models.CharField(max_length=50)),
                ('starthost', models.CharField(max_length=50)),
                ('endhost', models.CharField(max_length=50)),
                ('oshost', models.CharField(max_length=50)),
                ('scan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LineaBaseApp.tb_scan')),
            ],
            options={
                'verbose_name': 'tb_host',
                'verbose_name_plural': 'tb_hosts',
                'ordering': ['idhost'],
            },
        ),
    ]
